version: '3.8'

services:
  proxy:
    image: nginx:latest
    container_name: proxy
    ports:
      - "80:80"  
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf 
    restart: 'always' 
  
  backend-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-server
    ports:
      - 3001:3001
    volumes:
      - ./env/.env:/sns/env/.env
      - ./src:/sns/src
    restart: "always"

  database-server:
      image: mysql:5.7
      restart: always
      environment:
        MYSQL_DATABASE: 'wantedsns'
        MYSQL_ROOT_PASSWORD: '1234'
        MYSQL_TCP_PORT: 3307
        TZ: 'Asia/Seoul'
      command:
        [
          'mysqld',
          '--character-set-server=utf8mb4',
          '--collation-server=utf8mb4_unicode_ci',
          # '--default-time-zone=+09:00',
          '--default-authentication-plugin=mysql_native_password',
        ]
      ports:
        - 3307:3307